approvedGitRepositories:
  - "github.com/lichtblick-suite/*"

changesetBaseRefs:
  - main
  - origin/main

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

patchFolder: ./patches

yarnPath: .yarn/yarn-wrapper.js
